#!/bin/bash

channels=(CRtau_MLL_lowmet_cuts CRtop_MLL_lowmet_cuts CRVV_MLL_lowmet_cuts CRtau_MLL_hghmet_cuts CRtop_MLL_hghmet_cuts CRVV_MLL_hghmet_cuts SRee_eMLLc_hghmet_cuts SRee_eMLLd_hghmet_cuts SRee_eMLLe_hghmet_cuts SRee_eMLLf_hghmet_cuts SRee_eMLLg_hghmet_cuts SRee_eMLLh_hghmet_cuts SRmm_eMLLa_hghmet_cuts SRmm_eMLLb_hghmet_cuts SRmm_eMLLc_hghmet_cuts SRmm_eMLLd_hghmet_cuts SRmm_eMLLe_hghmet_cuts SRmm_eMLLf_hghmet_cuts SRmm_eMLLg_hghmet_cuts SRmm_eMLLh_hghmet_cuts SRee_eMLLc_lowmet_deltaM_low_cuts SRee_eMLLd_lowmet_deltaM_low_cuts SRee_eMLLe_lowmet_deltaM_low_cuts SRee_eMLLf_lowmet_deltaM_low_cuts SRmm_eMLLa_lowmet_deltaM_low_cuts SRmm_eMLLb_lowmet_deltaM_low_cuts SRmm_eMLLc_lowmet_deltaM_low_cuts SRmm_eMLLd_lowmet_deltaM_low_cuts SRmm_eMLLe_lowmet_deltaM_low_cuts SRmm_eMLLf_lowmet_deltaM_low_cuts SRee_eMLLc_lowmet_deltaM_high_cuts SRee_eMLLd_lowmet_deltaM_high_cuts SRee_eMLLe_lowmet_deltaM_high_cuts SRee_eMLLf_lowmet_deltaM_high_cuts SRee_eMLLg_lowmet_deltaM_high_cuts SRee_eMLLh_lowmet_deltaM_high_cuts SRmm_eMLLa_lowmet_deltaM_high_cuts SRmm_eMLLb_lowmet_deltaM_high_cuts SRmm_eMLLc_lowmet_deltaM_high_cuts SRmm_eMLLd_lowmet_deltaM_high_cuts SRmm_eMLLe_lowmet_deltaM_high_cuts SRmm_eMLLf_lowmet_deltaM_high_cuts SRmm_eMLLg_lowmet_deltaM_high_cuts SRmm_eMLLh_lowmet_deltaM_high_cuts )
samples="MGPy8EG_A14N23LO_C1N2_WZ_175p0_135p0_2L2MET75_MadSpin,diboson,fakes,other,Zttjets,top"
workspace=$1
for channel in ${channels[*]};
do
    echo $channel
    YieldsTable.py -c $channel -s $samples -w $workspace
done
